### PR TITLE
Create Javascript

### PR DESCRIPTION
**Pull request by Dkeys4**
For courses and general knowledge.

### CODE REVIEW

**Comment by dixitt5** [comment]
hey @Dkeys4 , can you create a folder other than a file, so everyone can contribute to that folder, thanks :)

**Comment by Dkeys4** [comment]
Ok I sure will. Will the file count towards a pull request or only the folder?

**Comment by dixitt5** [comment]
@Dkeys4 pull request can be combined with both of them, can you create another folder called "Javascript" and add these files into it, as the current committed files are in the parent directory?

**Comment by Dkeys4** [comment]
Yes, I will figure out how to do...google it! Thank you!

**Comment by Dkeys4** [comment]
did i do the folder correctl

**Comment by dixitt5** [comment]
@Dkeys4 nope, still not a folder present, how about we do this, I created a folder named "Javascript" under the main scope, you can add js related files in it, and let me know and I'll review it.

**Comment by Dkeys4** [comment]
Sorry, I know I'm not very good at this but I did just make 2 or three more pull requests under the JavaScript folder. I am knew to this but want to become a programmer. Thank you for being kind and helpful. I just finished those pull requests, let me know if they are able to be merged. Thank you.

**Comment by dixitt5** [comment]
It's okay Dural, I have reviewed it and it's ready to merge. 

You can read these docs for an understanding of git: https://dangitgit.com/en

Cheers!

**Pull request merged**
