### PR TITLE
hacktoberfest2022

### PR DESCRIPTION
**Pull request by ayushaggarwal600**

### CODE REVIEW

**Review by dixitt5 — CHANGES_REQUESTED** [review]
add it into a correct directory rather than adding in root :)

**Comment by ayushaggarwal600** [comment]
Can you please elaborate more, I can't understand as I am a beginner.

**Comment by dixitt5** [comment]
@ayushaggarwal600 no worries , I'm gonna merge this right away.

Here is the thing I asked you to do
(Please try to learn as it will helpful to you ;)

- When you add a file just Make sure you add it in the appropriate directory.
- Your file is a cpp file , then you have to add it in the cpp folder , it's that easy.
- refer a YouTube video or a tutorial and play with it , you'll understand it easily.

**Comment by ayushaggarwal600** [comment]
Thank you so much sir, will definitely learn about it!

**Pull request merged**
