### PR TITLE
Create palindrome number explanation

### PR DESCRIPTION
**Pull request by Thanmaia**
Added an example to the existing palindrome number code so that it is easy to understand.

### CODE REVIEW

**Comment by dixitt5** [comment]
@Thanmaia please add particular extension of the file and raise a pr again :)

**Comment by Thanmaia** [comment]
Thankyou for remembering @dixitt5 ..As it is my first commit and because of lack of experience I forget to add extension. I have done it now and raised a new pr

**Comment by dixitt5** [comment]
@Thanmaia no worries my friend , I'm not able to see your new pr again can you specify what name does it have ?

**Comment by Thanmaia** [comment]
@dixitt5 Create palindromenumexample.c is the new name..

**Comment by dixitt5** [comment]
@Thanmaia  this pr is not showing the change , better if you create a new PR

**Comment by dixitt5** [comment]
Okay got it ;)

**Pull request closed without merging**
