### PR TITLE
hacktoberfest2022

### PR DESCRIPTION
**Pull request by priyanshuengine**

### CODE REVIEW

**Comment by dixitt5** [comment]
add it in the specific folder and raise a pr again :) @priyanshuengine

**Comment by priyanshuengine** [comment]
Added the files in a specific folder

**Comment by dixitt5** [comment]
@priyanshuengine nope it's still not in the specific folder

**Comment by dixitt5** [comment]
do it for this file just like u did in the latest pr that i've just merged @priyanshuengine

**Pull request closed without merging**
