### PR TITLE
Binary Tree Max Path

### PR DESCRIPTION
**Pull request by fizaayesha**

### CODE REVIEW

**Comment by dixitt5** [comment]
@fizaayesha Hey, can you remove the additional folder structure created, it should be a simple problem name file. thanks

**Comment by fizaayesha** [comment]
Could you please let me the know that exactly which folder structure I have to remove?

**Comment by dixitt5** [comment]
You don't have to create your name as folder to add the solution, please remove that :)

**Comment by fizaayesha** [comment]
Comments Resolved

**Pull request merged**
