### PR TITLE
Added a recent leetcode solution

### PR DESCRIPTION
**Pull request by heeba-khan**

### CODE REVIEW

**Comment by dixitt5** [comment]
@heeba-khan can you remove the package.json file in the commit :)

**Comment by heeba-khan** [comment]
Sure! I have removed it now and pushed again. Kindly check.

**Comment by heeba-khan** [comment]
I have removed the package.json file. Kindly check.

**Comment by heeba-khan** [comment]
Sure! I have done it now.Kindly check it.

**Comment by heeba-khan** [comment]
I have updated the code and removed package.json . Kindly check.

**Comment by dixitt5** [comment]
Thanks for the changes, Merged!

**Pull request merged**
